# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-01 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualización')),
                ('estilista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.Estilista')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='citas.Categoria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estilistas',
            field=models.ManyToManyField(blank=True, null=True, related_name='servicios_realizados', to='citas.Estilista'),
        ),
    ]
