# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-01 18:14
from __future__ import unicode_literals

import common.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20230901_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='horarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='token_service',
            field=models.CharField(default=functools.partial(common.utils.generate_token, *('srv',), **{}), max_length=32, unique=True),
        ),
    ]
