# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-23 12:48
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20230908_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Reprogramada', 'Reprogramada'), ('No Asistió', 'No Asistió'), ('Cancelada', 'Cancelada'), ('Confirmada', 'Confirmada')], default='Programada', max_length=255),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token_service',
            field=models.CharField(default=functools.partial(common.utils.generate_token, *('res',), **{}), max_length=32, unique=True),
        ),
    ]
