"""
Django settings for proyecto_citas project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from decimal import Decimal
import os
import os.path
import environ

from django.conf import settings

def getenvvar(name, default_value=None):
    v = os.environ.get(name, default_value)
    if not v:
        raise Exception('Environment variable {} undefined'.format(name))
    return v

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.abspath(os.curdir)

root = environ.Path(__file__) - 4  # get root of the project
env = environ.Env()
environ.Env.read_env(os.path.join(root, '.env'))  # reading .env file

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEST_MODE = False

ALLOWED_HOSTS = [
    'localhost',
    '0.0.0.0',
    'ec2-34-204-78-207.compute-1.amazonaws.com'
]


# Application definition

LOCAL_INSTALLED_APPS = [
    'citas'
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + LOCAL_INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '..', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DEFAULT_DATABASE_NAME = 'default'
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    DEFAULT_DATABASE_NAME: {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'to-be-defined-by-other-settings-file',
        'USER': getenvvar('RDS_USERNAME'),
        'PASSWORD': getenvvar('RDS_PASSWORD'),
        'HOST': 'to-be-defined-by-other-settings-file',
        'PORT': 'to-be-defined-by-other-settings-file',
        'OPTIONS' : {'sslmode':'verify-full','sslrootcert':'/etc/ssl/certs/rds-combined-ca-bundle.pem'},
        'CONN_MAX_AGE': 300
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

BASE_URL = 'ec2-34-204-78-207.compute-1.amazonaws.com'
HTTP_PROTOCOL = 'http://'